[package]
name = "location_proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.1", default-features = false, features = ['std'] }
sha2 = "0.10.8"
serialport = "4.7.1"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"]}