[package]
name = "hardware_location"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.1"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"]}
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
futures-util = "0.3.31"